# Works only for Debian / Ubuntu so far
---
- name: Install OS updates
  hosts: "{{ target | default('bare_metal') }}"
  tasks:
    - name: apt upgrade
      ansible.builtin.apt:
        upgrade: full
        update_cache: yes
      become: true
