#SPDX-License-Identifier: MIT-0
---

bind_exporter_download_url_tpl: "https://github.com/prometheus-community/bind_exporter/releases/download/v{{ bind_exporter_version }}/bind_exporter-{{ bind_exporter_version }}."
bind_exporter_version: 0.8.0

  # These values will be auto-detected at runtime but can also be specified
# by the user, for example as --extra-vars or host_vars. If they are
# specified, the auto-detection will not run which makes the playbook a
# a little bit faster.
#
# For possible values, check the releases page of bind_exporter on github.com
# https://github.com/prometheus-community/bind_exporter/releases and see how
# OS type and arch values are used in the release filenames.

bind_exporter_os_type: ""
bind_exporter_os_arch: ""

bind_exporter_os_username: "bind_exporter"

bind_exporter_listen_address: ":9119"
bind_exporter_bind9_status_address: "http://localhost:8053"
