---
- name: Prepare - common
  hosts: all
  tasks:
    - name: Install OS packages
      ansible.builtin.apt:
        name: "{{ item }}"
      become: true
      loop:
        - vim
        - inetutils-ping
        - iproute2
        - curl
        - netcat-openbsd

- name: Prepare - ldap
  hosts: ldap
  gather_facts: false
  roles:
    - metashock_lab.ldap.openldap
    - metashock_lab.ldap.ldap_data
